### ISSUE TITLE
ValueError: File cannot be fetched

### ISSUE THREAD

**Issue by Nedrozak** [ttio2tech/model_converting_to_onnx#1]
I get his error after clicking the Submit button in the WebUI

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\starlette\applications.py", line 124, in __call__    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\gradio\routes.py", line 329, in file_deprecated
    return await file(path, request)
  File "C:\Users\Georgi\.conda\envs\stable_diffusion\lib\site-packages\gradio\routes.py", line 323, in file
    raise ValueError(
ValueError: File cannot be fetched: discord_server_invite2.png. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.

**Comment by Nedrozak** [comment]
Error is caused by quotes "" in the file path to the model, removing them fixes the error.
